
name: feature-pipeline

on:
  push:
    branches-ignore:
    - master
    - stage

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: run pipeline logic
      uses: intelligogroup/actions_feature-pipeline@master
      with:
        email_address: rnd@intelligo.ai
        username: "github-action-${{ github.workflow }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}

